name: Build Test Artifact

on:
  pull_request:
  push:
    branches: [ master ]
    tags:
      - '*'
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test For example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Gather Gradle properties
        uses: madhead/read-java-properties@latest
        id: gradle_properties
        with:
          file: gradle.properties
          all: true

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Change mod version
        run: sed -i "s/mod_version.*=.*/mod_version = ${{ steps.date.outputs.date }}/g" gradle.properties

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'  
          distribution: 'temurin'  
          cache: gradle
          
      - name: Update Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=8.5
        
      - name: Build
        uses: gradle/actions/setup-gradle@v3  
        with:
          gradle-version: wrapper

      - name: Clean and Build with warnings
        run: |
          ./gradlew clean
          ./gradlew build --warning-mode all --info --stacktrace

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: success()  
        with:
          name: ${{ steps.gradle_properties.outputs.mod_id }}-1.12.2-${{ steps.date.outputs.date }}-${{ github.run_number }}
          path: build/libs
          retention-days: 30  
