name: Build and Release Minecraft 1.12.2 Forge Mod

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release Forge Mod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Gather Gradle properties
        uses: madhead/read-java-properties@latest
        id: gradle_properties
        with:
          file: gradle.properties
          all: true

      - name: Get release version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=${{ steps.gradle_properties.outputs.mod_version }}
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Release version: ${VERSION}"

      - name: Update mod version for release
        run: |
          sed -i "s/mod_version.*=.*/mod_version = ${{ steps.version.outputs.VERSION }}/g" gradle.properties
          echo "Updated mod_version to: ${{ steps.version.outputs.VERSION }}"

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --info --stacktrace

      - name: List built files
        run: |
          echo "Files in build/libs:"
          ls -la build/libs/

      - name: Find built jar files
        id: find_jars
        run: |
          # 查找编译好的 jar 文件
          MAIN_JAR=$(find build/libs -name "*.jar" ! -name "*-sources.jar" ! -name "*-dev.jar" ! -name "*-deobf.jar" | head -1)
          SOURCES_JAR=$(find build/libs -name "*-sources.jar" | head -1)
          DEV_JAR=$(find build/libs -name "*-dev.jar" | head -1)
          
          echo "MAIN_JAR=${MAIN_JAR}" >> $GITHUB_OUTPUT
          echo "SOURCES_JAR=${SOURCES_JAR}" >> $GITHUB_OUTPUT
          echo "DEV_JAR=${DEV_JAR}" >> $GITHUB_OUTPUT
          
          echo "Found main jar: ${MAIN_JAR}"
          if [ -f "$SOURCES_JAR" ]; then
            echo "Found sources jar: ${SOURCES_JAR}"
          fi
          if [ -f "$DEV_JAR" ]; then
            echo "Found dev jar: ${DEV_JAR}"
          fi

      - name: Generate checksums
        run: |
          cd build/libs
          for file in *.jar; do
            if [ -f "$file" ]; then
              sha256sum "$file" > "$file.sha256"
              echo "Generated checksum for: $file"
            fi
          done

      - name: Upload Build Artifacts (for workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.gradle_properties.outputs.mod_id }}-1.12.2-${{ steps.version.outputs.VERSION }}-${{ github.run_number }}
          path: build/libs

      - name: Upload jar files to release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*
          draft: false
          prerelease: false
          tag_name: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}
          name: ${{ steps.gradle_properties.outputs.mod_id }} v${{ steps.version.outputs.VERSION }}
          body: |
            ## ${{ steps.gradle_properties.outputs.mod_id }} v${{ steps.version.outputs.VERSION }}
            
            **Mod Information:**
            - **Mod ID:** ${{ steps.gradle_properties.outputs.mod_id }}
            - **Version:** ${{ steps.version.outputs.VERSION }}
            - **Minecraft Version:** 1.12.2
            - **Forge Version:** Compatible with Minecraft Forge 1.12.2
            - **Built with:** Java 21 + Gradle
            - **Build Date:** ${{ steps.date.outputs.date }}
            
            ### Files Description:
            - `*.jar` (without suffix) - Main mod file for production use
            - `*-sources.jar` - Source code archive (for developers)
            - `*-dev.jar` - Development version (for mod developers)
            - `*.sha256` - SHA256 checksum files for verification
            
            ### Installation Instructions:
            1. Download the main `.jar` file (without `-sources` or `-dev` suffix)
            2. Place it in your `.minecraft/mods/` folder
            3. Make sure you have Minecraft Forge 1.12.2 installed
            4. Launch Minecraft and enjoy!
            
            ### For Developers:
            - Use the `-sources.jar` file to view the source code
            - Use the `-dev.jar` file in your development environment
            - Verify file integrity using the provided SHA256 checksums
            
            ### Verification:
            ```bash
            # Verify file integrity (Linux/macOS)
            sha256sum -c filename.jar.sha256
            
            # Verify file integrity (Windows PowerShell)
            Get-FileHash filename.jar -Algorithm SHA256
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT